# Basic
title: YorrickBao's Blog
subtitle: An iOS developer, swift fanatic
welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
description: Welcome.
creator: <a href="http://www.YorrickBao.com">@YorrickBao</a>
#<a href="http://onev.cat">@onevcat</a>

url: "http://www.YorrickBao.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color:

# The blog button should not be removed.
blog_button:
    title: 博客
    description: Visit blog

# Navigation buttons in the front page.
nav:
    # - {title: Projects, description: My Projects, url: 'http://onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://onevcat.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo:

# Social
social:
    #weibo: YorrickBao
    github: YorrickBao
    twitter: YorrickBao
    #gplus: 107108267983477358170
    mail: Yorrick.Bao@126.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
